### ISSUE TITLE
ReVac is not reproducible.

### ISSUE THREAD

**Issue by abrozzi** [admelloGithub/ReVac-package#1]

**Comment by admelloGithub** [comment]
We are not currently actively maintaining the ReVac pipeline. However, the ReVac workflow package was designed to work using the Ergatis management system, after all the required tools and dependencies are installed. The paths such as "$;BCELL_EXEC$;=/home/admello/Desktop/bcell/predict_bcell.py" in the software.config document should be updated with a path to local installs of the required tools.

Note: Some of the tools that were used in ReVac have been updated since the original ReVac release. For instance, Bcell_pred is now Bcell-3.1 (with predict_bcell.py now refered to as predict_antibody_epitope.py). Please keep in mind that Ergatis and the individual tools used in ReVac were not provided in the ReVac package, and need to installed independently. ReVac was primarily a workflow that utilized all tools listed in the manuscript to generate the tables and results based on the ReVac scoring scheme. All results can also be reproduced outside of ReVac usage by using the scoring scheme on the associated tools described in detail in the manuscript.
